app:
  name: "MyMall"
  mode: "dev"
  port: 8081
log:
  level: "debug"
  filename: "MyMall.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "mysql"        # ← 改成服务名，这是唯一的区别
  port: 3306
  user: "root"
  password: "root"
  dbname: "oomall"
  max_open_conns: 200
  max_idle_conns: 50