// Code generated by mapper_gen.go; DO NOT EDIT.
package infra

import "MyMall/domain"

func toDomain(po *RegionPo) *domain.Region {
	return &domain.Region{
		ID: po.ID,
		ParentID: po.ParentID,
		Level: po.Level,
		AreaCode: po.AreaCode,
		ZipCode: po.ZipCode,
		CityCode: po.CityCode,
		Name: po.Name,
		ShortName: po.ShortName,
		MergerName: po.MergerName,
		Pinyin: po.Pinyin,
		Lng: po.Lng,
		Lat: po.Lat,
		Status: po.Status,
		CreatorID: po.CreatorID,
		CreatorName: po.CreatorName,
		ModifierID: po.ModifierID,
		ModifierName: po.ModifierName,
		CreatedAt: po.CreatedAt,
		UpdatedAt: po.UpdatedAt,
	}
}

func toPo(region *domain.Region) *RegionPo {
	return &RegionPo{
		ID: region.ID,
		ParentID: region.ParentID,
		Level: region.Level,
		AreaCode: region.AreaCode,
		ZipCode: region.ZipCode,
		CityCode: region.CityCode,
		Name: region.Name,
		ShortName: region.ShortName,
		MergerName: region.MergerName,
		Pinyin: region.Pinyin,
		Lng: region.Lng,
		Lat: region.Lat,
		Status: region.Status,
		CreatorID: region.CreatorID,
		CreatorName: region.CreatorName,
		ModifierID: region.ModifierID,
		ModifierName: region.ModifierName,
		CreatedAt: region.CreatedAt,
		UpdatedAt: region.UpdatedAt,
	}
}
