// Code generated by mapper_gen.go; DO NOT EDIT.
package infra

import "MyMall/domain"

func toDomain(po *RegionPo) *domain.Region {
	return &domain.Region{
		Id:           po.Id,
		Pid:          po.Pid,
		Level:        po.Level,
		AreaCode:     po.AreaCode,
		ZipCode:      po.ZipCode,
		CityCode:     po.CityCode,
		Name:         po.Name,
		ShortName:    po.ShortName,
		MergerName:   po.MergerName,
		Pinyin:       po.Pinyin,
		Lng:          po.Lng,
		Lat:          po.Lat,
		Status:       po.Status,
		CreatorId:    po.CreatorId,
		CreatorName:  po.CreatorName,
		ModifierId:   po.ModifierId,
		ModifierName: po.ModifierName,
		GmtCreate:    po.GmtCreate,
		GmtModified:  po.GmtModified,
	}
}

func toPo(region *domain.Region) *RegionPo {
	return &RegionPo{
		Id:           region.Id,
		Pid:          region.Pid,
		Level:        region.Level,
		AreaCode:     region.AreaCode,
		ZipCode:      region.ZipCode,
		CityCode:     region.CityCode,
		Name:         region.Name,
		ShortName:    region.ShortName,
		MergerName:   region.MergerName,
		Pinyin:       region.Pinyin,
		Lng:          region.Lng,
		Lat:          region.Lat,
		Status:       region.Status,
		CreatorId:    region.CreatorId,
		CreatorName:  region.CreatorName,
		ModifierId:   region.ModifierId,
		ModifierName: region.ModifierName,
		GmtCreate:    region.GmtCreate,
		GmtModified:  region.GmtModified,
	}
}
