CREATE TABLE IF NOT EXISTS region_region (
                                             id            BIGINT        NOT NULL AUTO_INCREMENT,
                                             pid           BIGINT        NOT NULL DEFAULT 0,
                                             level         TINYINT       NOT NULL DEFAULT 0,
                                             area_code     VARCHAR(32)   NOT NULL DEFAULT '',
    zip_code      VARCHAR(32)   NOT NULL DEFAULT '',
    city_code     VARCHAR(32)   NOT NULL DEFAULT '',
    name          VARCHAR(128)  NOT NULL DEFAULT '',
    short_name    VARCHAR(64)   NOT NULL DEFAULT '',
    merger_name   VARCHAR(255)  NOT NULL DEFAULT '',
    pinyin        VARCHAR(255)  NOT NULL DEFAULT '',
    lng           DOUBLE        NOT NULL DEFAULT 0,
    lat           DOUBLE        NOT NULL DEFAULT 0,
    status        TINYINT       NOT NULL DEFAULT 0,
    creator_id    BIGINT        NOT NULL DEFAULT 0,
    creator_name  VARCHAR(64)   NOT NULL DEFAULT '',
    modifier_id   BIGINT        NOT NULL DEFAULT 0,
    modifier_name VARCHAR(64)   NOT NULL DEFAULT '',
    gmt_create    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;